name: Nightly Security Audit

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Run pip-audit (non-blocking)
        continue-on-error: true
        run: |
          pip-audit -f json -o pip-audit.json || true

      - name: Upload pip-audit report
        uses: actions/upload-artifact@v4
        with:
          name: nightly-pip-audit
          path: pip-audit.json
          if-no-files-found: warn

